services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx-rtsp
    restart: unless-stopped
    volumes:
      - ./config/mediamtx.yml:/mediamtx.yml
      - ./config/server.key:/server.key
      - ./config/server.crt:/server.crt
    ports:
      - 8554:8554
      - 8322:8322
      - 1935:1935
      - 8888:8888
      - 8889:8889
